{{ $_ := .Values.werf.env | set . "env" }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Chart.Name }}-{{ .Values.werf.env }}
spec:
  serviceName: {{ .Chart.Name }}-{{ .Values.werf.env }}
  replicas: 1
  selector:
      matchLabels:
        app: {{ .Chart.Name }}-{{ .Values.werf.env }}
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-{{ .Values.werf.env }}
    spec:
      containers:
      - name: gitlab-ce
        image: {{ .Values.werf.image.gitlab_ce }}
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        - containerPort: 22
{{- range $key, $item := .Values.hostPort }}
{{- if (eq $.env $item.env) }}
          hostPort: {{ $item.port }}
{{- end }}
{{- end }}
          name: ssh
          protocol: TCP
        startupProbe:
          httpGet:
            path: /users/sign_in
            port: http
          failureThreshold: 60
          periodSeconds: 10
        volumeMounts:
          - name: data-store
            mountPath: /etc/gitlab
            subPath: {{ .Chart.Name }}-config
          - name: data-store
            mountPath: /var/log/gitlab
            subPath: {{ .Chart.Name }}-logs
          - name: data-store
            mountPath: /var/opt/gitlab
            subPath: {{ .Chart.Name }}-data
      volumes:
      - name: data-store
        persistentVolumeClaim:
          claimName: nfs-pvc-{{ .Chart.Name }}-{{ .Values.werf.env }}
