apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Chart.Name }}-runner-{{ .Values.werf.env }}
spec:
  serviceName: {{ .Chart.Name }}-runner-{{ .Values.werf.env }}
  replicas: 1
  selector:
      matchLabels:
        app: {{ .Chart.Name }}-runner-{{ .Values.werf.env }}
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-runner-{{ .Values.werf.env }}
    spec:
      containers:
      - name: gitlab-runner
        image: {{ .Values.werf.image.gitlab_runner }}
        volumeMounts:
          - name: data-store
            mountPath: /etc/gitlab-runner
            subPath: {{ .Chart.Name }}-runner-config
          - name: docker-socket
            mountPath: /var/run/docker.sock
      initContainers:
{{- $gitlabUrl := "http://gitlab-prod.gitlab-prod/help" }}
{{- include "h-init-container-wait-http-200" (list $ . $gitlabUrl) | indent 6 }}
      volumes:
      - name: data-store
        persistentVolumeClaim:
          claimName: nfs-pvc-{{ .Chart.Name }}-{{ .Values.werf.env }}
      - name: docker-socket
        hostPath:
          path: /var/run/docker.sock
