apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-{{ .Values.werf.env }}
  labels:
    app: {{ .Chart.Name }}-{{ .Values.werf.env }}
spec:
  clusterIP: None
  selector:
    app: {{ .Chart.Name }}-{{ .Values.werf.env }}
  ports:
  - name: http
    port: 80
    protocol: TCP
  - name: ssh
    port: 2222
    protocol: TCP
    targetPort: 22
