apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-deployment
spec:
  replicas: 1
  selector:
      matchLabels:
        app: {{ .Chart.Name }}-deployment
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        ingressInternal: "yes"
        ingressExternal: "yes"
        app: {{ .Chart.Name }}-deployment
    spec:
      containers:
      - name: nginx
        {{ tuple (printf "%s-%s" .Chart.Name "nginx") . | werf_container_image }}
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        volumeMounts:
          - name: data-store
            mountPath: /usr/share/nginx/html
            subPath: skeleton-nginx
      volumes:
      - name: data-store
        persistentVolumeClaim:
          claimName: nfs-pvc-data-store
