apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-deployment
spec:
  replicas: 1
  selector:
      matchLabels:
        app: {{ .Chart.Name }}-deployment
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        ingressInternal: "yes"
        ingressExternal: "yes"
        app: {{ .Chart.Name }}-deployment
    spec:
      containers:
      - name: nginx
        {{ tuple (printf "%s-%s" .Chart.Name "nginx") . | werf_container_image }}
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        volumeMounts:
          - name: config-volume
            subPath: nginx.conf
            mountPath: /etc/nginx/nginx.conf
          - name: data-store
            mountPath: /var/www
            subPath: {{ .Chart.Name }}-www
      - name: php-fpm
        {{ tuple (printf "%s-%s" .Chart.Name "php-fpm") . | werf_container_image }}
        ports:
        - containerPort: 9000
          name: http
          protocol: TCP
        volumeMounts:
          - name: data-store
            mountPath: /var/www
            subPath: {{ .Chart.Name }}-www
      volumes:
      - name: config-volume
        configMap:
          name: {{ .Chart.Name }}-config-files
      - name: data-store
        persistentVolumeClaim:
          claimName: nfs-pvc-{{ .Chart.Name }}-{{ env "environment" }}
