kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs-pvc-data-store
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Gi
  volumeName: "nfs-pv-data-store"
