apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Chart.Name }}-statefulset-{{ env "environment" }}
spec:
  serviceName: {{ .Chart.Name }}-statefulset-{{ env "environment" }}
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-statefulset-{{ env "environment" }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-statefulset-{{ env "environment" }}
    spec:
      containers:
      - name: php-fpm
        {{ tuple (printf "%s-%s" .Chart.Name "php-fpm") . | werf_container_image }}
        ports:
        - containerPort: 9000
          name: http
          protocol: TCP
        env:
        - name: SSH_AUTH_SOCK
          value: /ssh-agent
        volumeMounts:
          - name: ssh-agent-sock
            mountPath: /ssh-agent
      - name: mariadb
        {{ tuple (printf "%s-%s" .Chart.Name "mariadb") . | werf_container_image }}
        ports:
        - containerPort: 3306
          name: mysql
          protocol: TCP
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: root
        volumeMounts:
        - name: data-store
          mountPath: /var/lib/mysql
          subPath: {{ .Chart.Name }}-mariadb
      - name: mongodb
        {{ tuple (printf "%s-%s" .Chart.Name "mongodb") . | werf_container_image }}
        ports:
        - containerPort: 27017
          name: mongod
          protocol: TCP
        volumeMounts:
        - name: data-store
          mountPath: /data/db
          subPath: {{ .Chart.Name }}-mongodb
      volumes:
      - name: config-volume
        configMap:
          name: {{ .Chart.Name }}-config-files
      - name: data-store
        persistentVolumeClaim:
          claimName: nfs-pvc-{{ .Chart.Name }}-{{ env "environment" }}
      - name: ssh-agent-sock
        hostPath:
          path: /ssh-agent
          type: Socket
