apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-fluentd-config-{{ env "environment" }}
  namespace: kube-system
data:
  myfilter.conf: |
    <match fluent.**>
      @type null
    </match>
    <match fluentd.**>
      @type null
    </match>
    <match kubernetes.var.log.containers.**fluentd**.log>
      @type null
    </match>
    #<match kubernetes.var.log.containers.**kube-system**.log>
    #  @type null
    #</match>
    <match kubernetes.var.log.containers.**kibana**.log>
      @type null
    </match>
    <filter kubernetes.**>
      @id filter_parser
      @type parser
      key_name log
      reserve_data true
      remove_key_name_field false
      replace_invalid_sequence true
      reserve_time true
      inject_key_prefix log_
      <parse>
        @type multi_format
        <pattern>
          remove_key_name_field false
          format json
          json_parser json
        </pattern>
        <pattern>
          format none
        </pattern>
      </parse>
    </filter>
