apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-kibana-{{ env "environment" }}
  labels:
    service: {{ .Chart.Name }}-kibana-{{ env "environment" }}
spec:
  type: NodePort
  selector:
    run: {{ .Chart.Name }}-kibana-{{ env "environment" }}
  ports:
  - port: 5601
    targetPort: 5601
