{{ $_ := env "environment" | set . "env" }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Chart.Name }}-runner-{{ env "environment" }}
spec:
  serviceName: {{ .Chart.Name }}-runner-{{ env "environment" }}
  replicas: 1
  selector:
      matchLabels:
        app: {{ .Chart.Name }}-runner-{{ env "environment" }}
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-runner-{{ env "environment" }}
    spec:
      containers:
      - name: gitlab-runner
        {{ tuple (printf "%s-%s" .Chart.Name "runner") . | werf_container_image }}
        volumeMounts:
          - name: data-store
            mountPath: /etc/gitlab-runner
            subPath: {{ .Chart.Name }}-runner-config
          - name: docker-socket
            mountPath: /var/run/docker.sock
      initContainers:
{{- $gitlabUrl := "http://gitlab-prod.gitlab-prod/users/sign_in" }}
{{- include "h-init-container-wait-http-200" (list $ . $gitlabUrl) | indent 6 }}
      volumes:
      - name: data-store
        persistentVolumeClaim:
          claimName: nfs-pvc-{{ .Chart.Name }}-{{ env "environment" }}
      - name: docker-socket
        hostPath:
          path: /var/run/docker.sock
