apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Chart.Name }}-{{ env "environment" }}
spec:
  serviceName: {{ .Chart.Name }}-{{ env "environment" }}
  replicas: 1
  selector:
      matchLabels:
        app: {{ .Chart.Name }}-{{ env "environment" }}
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-{{ env "environment" }}
    spec:
      containers:
      - name: gitlab
        {{ tuple (printf "%s-%s" .Chart.Name "gitlab") . | werf_container_image }}
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        - containerPort: 22
          hostPort: 2222
          name: ssh
          protocol: TCP
        volumeMounts:
          - name: data-store
            mountPath: /etc/gitlab
            subPath: {{ .Chart.Name }}-config
          - name: data-store
            mountPath: /var/log/gitlab
            subPath: {{ .Chart.Name }}-logs
          - name: data-store
            mountPath: /var/opt/gitlab
            subPath: {{ .Chart.Name }}-data
      volumes:
      - name: data-store
        persistentVolumeClaim:
          claimName: nfs-pvc-{{ .Chart.Name }}-{{ env "environment" }}
