apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-statefulset
  labels:
    app: {{ .Chart.Name }}-statefulset
spec:
  clusterIP: None
  selector:
    app: {{ .Chart.Name }}-statefulset
  ports:
  - name: http
    port: 80
    protocol: TCP
  - name: ssh
    port: 2222
    protocol: TCP
    targetPort: 22
