#!/bin/bash

HOME_USER_NAME=user
HOME_USER_EMAIL=user@email.loc
HOME_SSH_HOST=127.0.0.1
HOME_SSH_PORT=80
HOME_NODEJS_VERSION=14.15.1
HOME_MINIKUBE_CPU=3
HOME_MINIKUBE_MEM=4096
HOME_VIM_INDENT_JS=2
HOME_VIM_INDENT_CSS=2
HOME_VIM_INDENT_JSON=2
HOME_VIM_INDENT_PHP=4
HOME_VIM_INDENT_SHELL=4
